name:                      Jekyll Ci Workflow

on:
  push:
    branches:
      -  main
  pull_request:
    branches:
      -  main
  workflow_dispatch:

env:
  DOCKER_USER:             "mmaffaitdevoteam"
  DOCKER_IMAGE:            "jklresume"

jobs:
  build:
    name:                  "Jekyll => Build and Upload"
    runs-on:               ubuntu-latest
    steps:
    - name:                "Init => Run checkout@v2"
      uses:                actions/checkout@v2
    - name:                "Build => Build the site in the jekyll/builder container"
      run:                 |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name:                "Upload => Upload Jekyll buid as a artifact"
      uses:                actions/upload-artifact@v2
      with:
        name:              jekyll-resume-tpl
        path:              ${{ github.workspace }}/_site
        if-no-files-found: error
        retention-days:    7
  docker:
      name:                "Docker => Build and Push"
      runs-on:             ubuntu-latest
      needs:
        - build
      steps:
        - name:            "Init => Checkout"
          uses:            actions/checkout@v2
        - name:            "Init => Download previous artifact"
          uses:            actions/download-artifact@v2
          with:
            name:          jekyll-resume-tpl
            path:          ${{ github.workspace }}/_site
        - name:            "Prepare => Docker meta"
          id:              docker_meta
          uses:            docker/metadata-action@v3
          with:
            images:        ghcr.io/${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE }}
            tags:          |
              type=schedule,pattern=nightly
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{ version }}
        - name:            "Docker => Login to GitHub Container Registry"
          uses:            docker/login-action@v1
          with:
            registry:      ghcr.io
            username:      ${{ github.repository_owner }}
            password:      ${{ secrets.GITHUB_TOKEN }}
        - name:            "Docker => Set up Docker Buildx"
          id:              buildx
          uses:            docker/setup-buildx-action@v1
          with:
            version:       latest
        - name:            "Docker => Build and push"
          id:              docker_build
          uses:            docker/build-push-action@v2
          with:
            context:       .
            file:          ./Dockerfile
            platforms:     linux/amd64
            push:          true
            tags:          ${{ steps.docker_meta.outputs.tags }}
            labels:        ${{ steps.docker_meta.outputs.labels }}
        - name:            "Docker => Image digest"
          run:             echo ${{ steps.docker_build.outputs.digest }}
